/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, email: {
                    name: "email",
                    type: "String",
                }, emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, sessions: {
                    name: "sessions",
                    type: "Session",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, accounts: {
                    name: "accounts",
                    type: "Account",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, vehicles: {
                    name: "vehicles",
                    type: "Vehicle",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, theme: {
                    name: "theme",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "light" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        session: {
            name: 'Session', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, token: {
                    name: "token",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    isOptional: true,
                }, userAgent: {
                    name: "userAgent",
                    type: "String",
                    isOptional: true,
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'sessions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, token: {
                    name: "token",
                    fields: ["token"]
                },
            },
        },
        account: {
            name: 'Account', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, accountId: {
                    name: "accountId",
                    type: "String",
                }, providerId: {
                    name: "providerId",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'accounts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, accessToken: {
                    name: "accessToken",
                    type: "String",
                    isOptional: true,
                }, refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    isOptional: true,
                }, idToken: {
                    name: "idToken",
                    type: "String",
                    isOptional: true,
                }, accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, scope: {
                    name: "scope",
                    type: "String",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        verification: {
            name: 'Verification', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, identifier: {
                    name: "identifier",
                    type: "String",
                }, value: {
                    name: "value",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        vehicle: {
            name: 'Vehicle', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, type: {
                    name: "type",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "Carro" }] }],
                }, brand: {
                    name: "brand",
                    type: "String",
                }, model: {
                    name: "model",
                    type: "String",
                }, year: {
                    name: "year",
                    type: "Int",
                }, modelYear: {
                    name: "modelYear",
                    type: "Int",
                    isOptional: true,
                }, purchasePrice: {
                    name: "purchasePrice",
                    type: "Float",
                    isOptional: true,
                }, purchaseDate: {
                    name: "purchaseDate",
                    type: "DateTime",
                    isOptional: true,
                }, saleDate: {
                    name: "saleDate",
                    type: "DateTime",
                    isOptional: true,
                }, initialKm: {
                    name: "initialKm",
                    type: "Int",
                }, currentKm: {
                    name: "currentKm",
                    type: "Int",
                }, fipeCode: {
                    name: "fipeCode",
                    type: "String",
                    isOptional: true,
                }, notes: {
                    name: "notes",
                    type: "String",
                    isArray: true,
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'vehicles',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, technicalInfos: {
                    name: "technicalInfos",
                    type: "TechnicalInfo",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'vehicle',
                }, maintenanceRecords: {
                    name: "maintenanceRecords",
                    type: "MaintenanceRecord",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'vehicle',
                }, maintenanceCategories: {
                    name: "maintenanceCategories",
                    type: "MaintenanceCategory",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'vehicle',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        maintenanceCategory: {
            name: 'MaintenanceCategory', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, vehicleId: {
                    name: "vehicleId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'vehicle',
                }, vehicle: {
                    name: "vehicle",
                    type: "Vehicle",
                    isDataModel: true,
                    backLink: 'maintenanceCategories',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "vehicleId" },
                }, technicalInfos: {
                    name: "technicalInfos",
                    type: "TechnicalInfo",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                }, maintenanceRecords: {
                    name: "maintenanceRecords",
                    type: "MaintenanceRecord",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        technicalInfo: {
            name: 'TechnicalInfo', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, description: {
                    name: "description",
                    type: "String",
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, kmInterval: {
                    name: "kmInterval",
                    type: "Int",
                    isOptional: true,
                }, timeIntervalMonths: {
                    name: "timeIntervalMonths",
                    type: "Int",
                    isOptional: true,
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, category: {
                    name: "category",
                    type: "MaintenanceCategory",
                    isDataModel: true,
                    backLink: 'technicalInfos',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "categoryId" },
                }, vehicleId: {
                    name: "vehicleId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'vehicle',
                }, vehicle: {
                    name: "vehicle",
                    type: "Vehicle",
                    isDataModel: true,
                    backLink: 'technicalInfos',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "vehicleId" },
                }, maintenanceRecords: {
                    name: "maintenanceRecords",
                    type: "MaintenanceRecord",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'technicalInfo',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        maintenanceRecord: {
            name: 'MaintenanceRecord', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, date: {
                    name: "date",
                    type: "DateTime",
                }, kmAtService: {
                    name: "kmAtService",
                    type: "Int",
                }, description: {
                    name: "description",
                    type: "String",
                }, cost: {
                    name: "cost",
                    type: "Float",
                    isOptional: true,
                }, nextDate: {
                    name: "nextDate",
                    type: "DateTime",
                    isOptional: true,
                }, nextKm: {
                    name: "nextKm",
                    type: "Int",
                    isOptional: true,
                }, observations: {
                    name: "observations",
                    type: "String",
                    isOptional: true,
                }, attachments: {
                    name: "attachments",
                    type: "String",
                    isArray: true,
                }, ignored: {
                    name: "ignored",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, technicalInfoId: {
                    name: "technicalInfoId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'technicalInfo',
                }, technicalInfo: {
                    name: "technicalInfo",
                    type: "TechnicalInfo",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'maintenanceRecords',
                    isRelationOwner: true,
                    onDeleteAction: 'SetNull',
                    foreignKeyMapping: { "id": "technicalInfoId" },
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, category: {
                    name: "category",
                    type: "MaintenanceCategory",
                    isDataModel: true,
                    backLink: 'maintenanceRecords',
                    isRelationOwner: true,
                    onDeleteAction: 'Restrict',
                    foreignKeyMapping: { "id": "categoryId" },
                }, vehicleId: {
                    name: "vehicleId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'vehicle',
                }, vehicle: {
                    name: "vehicle",
                    type: "Vehicle",
                    isDataModel: true,
                    backLink: 'maintenanceRecords',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "vehicleId" },
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },

    },
    deleteCascade: {
        user: ['Session', 'Account', 'Vehicle'],
        vehicle: ['MaintenanceCategory', 'TechnicalInfo', 'MaintenanceRecord'],
        maintenanceCategory: ['TechnicalInfo'],

    },
    authModel: 'User'

};
export default metadata;
