/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, MaintenanceRecord } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateMaintenanceRecord(options?: Omit<(UseMutationOptions<(MaintenanceRecord | undefined), DefaultError, Prisma.MaintenanceRecordCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceRecordCreateArgs, DefaultError, MaintenanceRecord, true>('MaintenanceRecord', 'POST', `${endpoint}/maintenanceRecord/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceRecordCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceRecordCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceRecordCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyMaintenanceRecord(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MaintenanceRecordCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceRecordCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('MaintenanceRecord', 'POST', `${endpoint}/maintenanceRecord/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceRecordCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceRecordCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceRecordCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceRecordGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findMany`, args, options, fetch);
}

export function useInfiniteFindManyMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceRecordGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findMany`, args, options, fetch);
}

export function useSuspenseFindManyMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceRecordGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceRecordGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findMany`, args, options, fetch);
}

export function useFindUniqueMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindUniqueArgs, TQueryFnData = Prisma.MaintenanceRecordGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindUniqueArgs, TQueryFnData = Prisma.MaintenanceRecordGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findUnique`, args, options, fetch);
}

export function useFindFirstMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindFirstArgs, TQueryFnData = Prisma.MaintenanceRecordGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordFindFirstArgs, TQueryFnData = Prisma.MaintenanceRecordGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/findFirst`, args, options, fetch);
}

export function useUpdateMaintenanceRecord(options?: Omit<(UseMutationOptions<(MaintenanceRecord | undefined), DefaultError, Prisma.MaintenanceRecordUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceRecordUpdateArgs, DefaultError, MaintenanceRecord, true>('MaintenanceRecord', 'PUT', `${endpoint}/maintenanceRecord/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceRecordUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceRecordUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceRecordUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyMaintenanceRecord(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MaintenanceRecordUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceRecordUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('MaintenanceRecord', 'PUT', `${endpoint}/maintenanceRecord/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceRecordUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceRecordUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceRecordUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertMaintenanceRecord(options?: Omit<(UseMutationOptions<(MaintenanceRecord | undefined), DefaultError, Prisma.MaintenanceRecordUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceRecordUpsertArgs, DefaultError, MaintenanceRecord, true>('MaintenanceRecord', 'POST', `${endpoint}/maintenanceRecord/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceRecordUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceRecordUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceRecordUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteMaintenanceRecord(options?: Omit<(UseMutationOptions<(MaintenanceRecord | undefined), DefaultError, Prisma.MaintenanceRecordDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceRecordDeleteArgs, DefaultError, MaintenanceRecord, true>('MaintenanceRecord', 'DELETE', `${endpoint}/maintenanceRecord/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceRecordDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceRecordDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceRecordDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceRecord, Prisma.MaintenanceRecordGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyMaintenanceRecord(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MaintenanceRecordDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceRecordDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('MaintenanceRecord', 'DELETE', `${endpoint}/maintenanceRecord/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceRecordDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceRecordDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceRecordDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordAggregateArgs, TQueryFnData = Prisma.GetMaintenanceRecordAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordAggregateArgs, TQueryFnData = Prisma.GetMaintenanceRecordAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/aggregate`, args, options, fetch);
}

export function useGroupByMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MaintenanceRecordGroupByArgs['orderBy'] } : { orderBy?: Prisma.MaintenanceRecordGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MaintenanceRecordGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.MaintenanceRecordGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceRecordGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceRecordGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MaintenanceRecordGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MaintenanceRecordGroupByArgs['orderBy'] } : { orderBy?: Prisma.MaintenanceRecordGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MaintenanceRecordGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.MaintenanceRecordGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceRecordGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceRecordGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MaintenanceRecordGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/groupBy`, args, options, fetch);
}

export function useCountMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MaintenanceRecordCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/count`, args, options, fetch);
}

export function useSuspenseCountMaintenanceRecord<TArgs extends Prisma.MaintenanceRecordCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MaintenanceRecordCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceRecordCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/count`, args, options, fetch);
}

export function useCheckMaintenanceRecord<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; kmAtService?: number; description?: string; nextKm?: number; observations?: string; attachments?: string; ignored?: boolean; technicalInfoId?: string; categoryId?: string; vehicleId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('MaintenanceRecord', `${endpoint}/maintenanceRecord/check`, args, options, fetch);
}
