/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, MaintenanceCategory } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateMaintenanceCategory(options?: Omit<(UseMutationOptions<(MaintenanceCategory | undefined), DefaultError, Prisma.MaintenanceCategoryCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceCategoryCreateArgs, DefaultError, MaintenanceCategory, true>('MaintenanceCategory', 'POST', `${endpoint}/maintenanceCategory/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceCategoryCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceCategoryCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceCategoryCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyMaintenanceCategory(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MaintenanceCategoryCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceCategoryCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('MaintenanceCategory', 'POST', `${endpoint}/maintenanceCategory/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceCategoryCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceCategoryCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceCategoryCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceCategoryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findMany`, args, options, fetch);
}

export function useInfiniteFindManyMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceCategoryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findMany`, args, options, fetch);
}

export function useSuspenseFindManyMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceCategoryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindManyArgs, TQueryFnData = Array<Prisma.MaintenanceCategoryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findMany`, args, options, fetch);
}

export function useFindUniqueMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindUniqueArgs, TQueryFnData = Prisma.MaintenanceCategoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindUniqueArgs, TQueryFnData = Prisma.MaintenanceCategoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findUnique`, args, options, fetch);
}

export function useFindFirstMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindFirstArgs, TQueryFnData = Prisma.MaintenanceCategoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryFindFirstArgs, TQueryFnData = Prisma.MaintenanceCategoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/findFirst`, args, options, fetch);
}

export function useUpdateMaintenanceCategory(options?: Omit<(UseMutationOptions<(MaintenanceCategory | undefined), DefaultError, Prisma.MaintenanceCategoryUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceCategoryUpdateArgs, DefaultError, MaintenanceCategory, true>('MaintenanceCategory', 'PUT', `${endpoint}/maintenanceCategory/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceCategoryUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceCategoryUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceCategoryUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyMaintenanceCategory(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MaintenanceCategoryUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceCategoryUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('MaintenanceCategory', 'PUT', `${endpoint}/maintenanceCategory/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceCategoryUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceCategoryUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceCategoryUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertMaintenanceCategory(options?: Omit<(UseMutationOptions<(MaintenanceCategory | undefined), DefaultError, Prisma.MaintenanceCategoryUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceCategoryUpsertArgs, DefaultError, MaintenanceCategory, true>('MaintenanceCategory', 'POST', `${endpoint}/maintenanceCategory/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceCategoryUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceCategoryUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceCategoryUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteMaintenanceCategory(options?: Omit<(UseMutationOptions<(MaintenanceCategory | undefined), DefaultError, Prisma.MaintenanceCategoryDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceCategoryDeleteArgs, DefaultError, MaintenanceCategory, true>('MaintenanceCategory', 'DELETE', `${endpoint}/maintenanceCategory/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceCategoryDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceCategoryDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceCategoryDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MaintenanceCategory, Prisma.MaintenanceCategoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyMaintenanceCategory(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MaintenanceCategoryDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MaintenanceCategoryDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('MaintenanceCategory', 'DELETE', `${endpoint}/maintenanceCategory/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MaintenanceCategoryDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MaintenanceCategoryDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MaintenanceCategoryDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryAggregateArgs, TQueryFnData = Prisma.GetMaintenanceCategoryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryAggregateArgs, TQueryFnData = Prisma.GetMaintenanceCategoryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/aggregate`, args, options, fetch);
}

export function useGroupByMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MaintenanceCategoryGroupByArgs['orderBy'] } : { orderBy?: Prisma.MaintenanceCategoryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MaintenanceCategoryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.MaintenanceCategoryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceCategoryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceCategoryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MaintenanceCategoryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MaintenanceCategoryGroupByArgs['orderBy'] } : { orderBy?: Prisma.MaintenanceCategoryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MaintenanceCategoryGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.MaintenanceCategoryGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceCategoryGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.MaintenanceCategoryGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MaintenanceCategoryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/groupBy`, args, options, fetch);
}

export function useCountMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MaintenanceCategoryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/count`, args, options, fetch);
}

export function useSuspenseCountMaintenanceCategory<TArgs extends Prisma.MaintenanceCategoryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MaintenanceCategoryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MaintenanceCategoryCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/count`, args, options, fetch);
}

export function useCheckMaintenanceCategory<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; userId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('MaintenanceCategory', `${endpoint}/maintenanceCategory/check`, args, options, fetch);
}
