/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, TechnicalInfo } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTechnicalInfo(options?: Omit<(UseMutationOptions<(TechnicalInfo | undefined), DefaultError, Prisma.TechnicalInfoCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TechnicalInfoCreateArgs, DefaultError, TechnicalInfo, true>('TechnicalInfo', 'POST', `${endpoint}/technicalInfo/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TechnicalInfoCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TechnicalInfoCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TechnicalInfoCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTechnicalInfo(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TechnicalInfoCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TechnicalInfoCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TechnicalInfo', 'POST', `${endpoint}/technicalInfo/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TechnicalInfoCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TechnicalInfoCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TechnicalInfoCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindManyArgs, TQueryFnData = Array<Prisma.TechnicalInfoGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindManyArgs, TQueryFnData = Array<Prisma.TechnicalInfoGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindManyArgs, TQueryFnData = Array<Prisma.TechnicalInfoGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindManyArgs, TQueryFnData = Array<Prisma.TechnicalInfoGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findMany`, args, options, fetch);
}

export function useFindUniqueTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindUniqueArgs, TQueryFnData = Prisma.TechnicalInfoGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindUniqueArgs, TQueryFnData = Prisma.TechnicalInfoGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findUnique`, args, options, fetch);
}

export function useFindFirstTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindFirstArgs, TQueryFnData = Prisma.TechnicalInfoGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTechnicalInfo<TArgs extends Prisma.TechnicalInfoFindFirstArgs, TQueryFnData = Prisma.TechnicalInfoGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/findFirst`, args, options, fetch);
}

export function useUpdateTechnicalInfo(options?: Omit<(UseMutationOptions<(TechnicalInfo | undefined), DefaultError, Prisma.TechnicalInfoUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TechnicalInfoUpdateArgs, DefaultError, TechnicalInfo, true>('TechnicalInfo', 'PUT', `${endpoint}/technicalInfo/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TechnicalInfoUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TechnicalInfoUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TechnicalInfoUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTechnicalInfo(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TechnicalInfoUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TechnicalInfoUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TechnicalInfo', 'PUT', `${endpoint}/technicalInfo/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TechnicalInfoUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TechnicalInfoUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TechnicalInfoUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTechnicalInfo(options?: Omit<(UseMutationOptions<(TechnicalInfo | undefined), DefaultError, Prisma.TechnicalInfoUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TechnicalInfoUpsertArgs, DefaultError, TechnicalInfo, true>('TechnicalInfo', 'POST', `${endpoint}/technicalInfo/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TechnicalInfoUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TechnicalInfoUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TechnicalInfoUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTechnicalInfo(options?: Omit<(UseMutationOptions<(TechnicalInfo | undefined), DefaultError, Prisma.TechnicalInfoDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TechnicalInfoDeleteArgs, DefaultError, TechnicalInfo, true>('TechnicalInfo', 'DELETE', `${endpoint}/technicalInfo/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TechnicalInfoDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TechnicalInfoDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TechnicalInfoDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TechnicalInfo, Prisma.TechnicalInfoGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTechnicalInfo(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TechnicalInfoDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TechnicalInfoDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TechnicalInfo', 'DELETE', `${endpoint}/technicalInfo/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TechnicalInfoDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TechnicalInfoDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TechnicalInfoDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTechnicalInfo<TArgs extends Prisma.TechnicalInfoAggregateArgs, TQueryFnData = Prisma.GetTechnicalInfoAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTechnicalInfo<TArgs extends Prisma.TechnicalInfoAggregateArgs, TQueryFnData = Prisma.GetTechnicalInfoAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/aggregate`, args, options, fetch);
}

export function useGroupByTechnicalInfo<TArgs extends Prisma.TechnicalInfoGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TechnicalInfoGroupByArgs['orderBy'] } : { orderBy?: Prisma.TechnicalInfoGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TechnicalInfoGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TechnicalInfoGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TechnicalInfoGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TechnicalInfoGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TechnicalInfoGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTechnicalInfo<TArgs extends Prisma.TechnicalInfoGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TechnicalInfoGroupByArgs['orderBy'] } : { orderBy?: Prisma.TechnicalInfoGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TechnicalInfoGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.TechnicalInfoGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.TechnicalInfoGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.TechnicalInfoGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TechnicalInfoGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/groupBy`, args, options, fetch);
}

export function useCountTechnicalInfo<TArgs extends Prisma.TechnicalInfoCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TechnicalInfoCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/count`, args, options, fetch);
}

export function useSuspenseCountTechnicalInfo<TArgs extends Prisma.TechnicalInfoCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TechnicalInfoCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TechnicalInfoCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TechnicalInfo', `${endpoint}/technicalInfo/count`, args, options, fetch);
}

export function useCheckTechnicalInfo<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; description?: string; notes?: string; kmInterval?: number; timeIntervalMonths?: number; categoryId?: string; vehicleId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TechnicalInfo', `${endpoint}/technicalInfo/check`, args, options, fetch);
}
